### ISSUE TITLE
might need TwythonError method to handle 404s

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/distro#3]
Currently, if you request a twitter handle that doesn't exist, the script falls over with a 404.  Looks like the `TwythonAuthError` only deals with private handles, and another method `TwythonError` deals with 404s.

I modified my helpers.py to import TwythonError

```
from twython.exceptions import TwythonError, TwythonAuthError
```

and changed the exception

```
except (TwythonError, TwythonAuthError):
    return None
```

and that worked for me.

**Comment by dmalan** [comment]
@curiouskiwi, @brianyu28 how does this look?

https://github.com/cs50/problems/pull/4

Overarching goal is not to expect students to use `try/except` yet but expect them to check for `None`. But if they hit an API limit or have invalid credentials, raising an uncaught exception in those cases so that students know why `get_user_timeline` is misbehaving feels reasonable.

**Comment by curiouskiwi** [comment]
@dmalan Looks like a more comprehensive solution than I proposed. Nice!
